spring.application.name=percentage-service

# this service does not run a web server
spring.main.web-application-type=none

#Der percentage-service liest aus energy_usage und schreibt in current_percentage.
spring.datasource.url=jdbc:postgresql://localhost:5432/energydb
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
