spring.application.name=energy-producer

# this app does not run a web server
spring.main.web-application-type=none

#Der Producer verbindet sich mit RabbitMQ auf localhost:5672.
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# location for the weather api (Vienna by default)
producer.weather.latitude=48.21
producer.weather.longitude=16.37
