# Die energy-api verbindet sich mit PostgreSQL und liest Daten die REST API.

spring.application.name=energy-api
spring.datasource.url=jdbc:postgresql://localhost:5432/energydb
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate soll die Tabellen nicht automatisch erstellen. Die Tabellen werden über Flyway erstellt.
spring.jpa.hibernate.ddl-auto=none
