spring.application.name=usage-service

# This service does not run a web server.
spring.main.web-application-type=none

# Der usage-service verbindet sich mit RabbitMQ, um Nachrichten zu empfangen und Updates zu senden.
# Der usage-service schreibt und verändert Daten in der Tabelle energy_usage.
spring.datasource.url=jdbc:postgresql://localhost:5432/energydb
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver

# The table is managed by energy-api via Flyway.
spring.jpa.hibernate.ddl-auto=none

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
